# Generated by Django 4.0.2 on 2022-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'viagem',
            },
        ),
    ]
